[package]
name = "fancy-garbling-base-conversion"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]

[build-dependencies]
cc.workspace = true

