[package]
name = "keyed_arena"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
bumpalo.workspace = true
crossbeam-queue.workspace = true
